import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import MaterialThemeProvider from '@/presentation/providers/MaterialThemeProvider'

export const montserratFont = Montserrat({
  subsets: ['latin'],
  weight: ['400', '600', '300'],
})

export const metadata: Metadata = {
  title: 'Case Meli',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={montserratFont.className}
      >
        <MaterialThemeProvider font={montserratFont}>
          {children}
        </MaterialThemeProvider>
      </body>
    </html>
  )
}
